FIX: config du serverCLAU

diff --git a/server/Jenkinsfile b/server/Jenkinsfile
--- a/server/Jenkinsfile
+++ b/server/Jenkinsfile
@@ -64,7 +64,6 @@ pipeline {
         stage('Quality Gate') {
             steps {
                 timeout(time: 15, unit: 'MINUTES') {
-                    // abortPipeline: false permet de continuer même si le gate met trop de temps
                     waitForQualityGate abortPipeline: false
                 }
             }
@@ -87,17 +86,32 @@ pipeline {
                     passwordVariable: 'ARTIF_PASS'
                 )]) {
                     dir('server') {
-                       sh """
-                            echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"><servers><server><id>artifactory</id><username>\${ARTIF_USER}</username><password>\${ARTIF_PASS}</password></server></servers></settings>' > settings_jenkins.xml
+                        sh """
+                            cat > settings_jenkins.xml << 'SETTINGSEOF'
+<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0">
+  <servers>
+    <server>
+      <id>artifactory</id>
+      <username>${ARTIF_USER}</username>
+      <password>${ARTIF_PASS}</password>
+    </server>
+  </servers>
+</settings>
+SETTINGSEOF
+
                             SERVICES="eureka_server users_service forums_service incident_service activities_service localization_service movement_service api_gateway"
+
                             for service in \$SERVICES; do
-                            echo "🚀 Déploiement forcé de : \$service"
-                            mvn deploy -U -DskipTests \\
-                            --settings ./settings_jenkins.xml \\
-                            -DaltDeploymentRepository="artifactory::http://172.19.224.221:8082/artifactory/libs-snapshot-local" \\
-                            -f \$service/pom.xml
+                                echo "🚀 Déploiement de : \$service"
+                                mvn deploy -DskipTests \
+                                  --settings ./settings_jenkins.xml \
+                                  -Dmaven.wagon.http.retryHandler.count=0 \
+                                  -DaltDeploymentRepository="artifactory::http://172.19.224.221:8082/artifactory/libs-snapshot-local" \
+                                  -f \$service/pom.xml || echo "⚠️ \$service deploy failed, continuing..."
                             done
-                          """
+
+                            echo "✅ Déploiement terminé !"
+                        """
                     }
                 }
             }
