FIX: config du servermodiff

diff --git a/server/Jenkinsfile b/server/Jenkinsfile
--- a/server/Jenkinsfile
+++ b/server/Jenkinsfile
@@ -86,32 +86,36 @@ pipeline {
                     passwordVariable: 'ARTIF_PASS'
                 )]) {
                     dir('server') {
-                        sh """
-                            cat > settings_jenkins.xml << 'SETTINGSEOF'
+                        sh '''
+                            cat > settings_jenkins.xml << SETTINGSEOF
 <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0">
   <servers>
     <server>
       <id>artifactory</id>
-      <username>${ARTIF_USER}</username>
-      <password>${ARTIF_PASS}</password>
+      <username>ARTIF_USER_PLACEHOLDER</username>
+      <password>ARTIF_PASS_PLACEHOLDER</password>
     </server>
   </servers>
 </settings>
 SETTINGSEOF
 
+                            sed -i "s/ARTIF_USER_PLACEHOLDER/${ARTIF_USER}/" settings_jenkins.xml
+                            sed -i "s/ARTIF_PASS_PLACEHOLDER/${ARTIF_PASS}/" settings_jenkins.xml
+
                             SERVICES="eureka_server users_service forums_service incident_service activities_service localization_service movement_service api_gateway"
 
-                            for service in \$SERVICES; do
-                                echo "🚀 Déploiement de : \$service"
+                            for service in $SERVICES; do
+                                echo "🚀 Déploiement de : $service"
                                 mvn deploy -DskipTests \
                                   --settings ./settings_jenkins.xml \
-                                  -Dmaven.wagon.http.retryHandler.count=0 \
-                                  -DaltDeploymentRepository="artifactory::http://172.19.224.221:8082/artifactory/libs-snapshot-local" \
-                                  -f \$service/pom.xml || echo "⚠️ \$service deploy failed, continuing..."
+                                  -Dmaven.resolver.transport=wagon \
+                                  -Daether.checksums.algorithms=MD5,SHA-1 \
+                                  -DaltDeploymentRepository="artifactory::default::http://172.19.224.221:8082/artifactory/libs-snapshot-local" \
+                                  -f $service/pom.xml || echo "⚠️ $service deploy failed, continuing..."
                             done
 
                             echo "✅ Déploiement terminé !"
-                        """
+                        '''
                     }
                 }
             }
